Api calcul chiffre
tiphainehenry/fhe_oracle pull request #1
Opened 2022-05-12 15:43 UTC by OsgoodSchlatter

2022-05-13 16:31 UTC, tiphainehenry requested changes

2022-05-13 16:31 UTC, tiphainehenry commented on src/utils/verif_FHE_comparison.cc
> +            case 0:
A quoi sert le case 0 ?

2022-05-13 16:31 UTC, tiphainehenry commented on README.md
> -==========
Je préfère garder l'ancienne syntaxe (syntaxe markdown)

2022-05-13 16:31 UTC, tiphainehenry commented on README.md
> +# fhe_oracle
Remetttre =====

2022-05-13 16:31 UTC, tiphainehenry commented on README.md
> --------
idem, mieux vaut garder la syntaxe markdown

2022-05-13 16:31 UTC, tiphainehenry commented on src/f_Oracle.cpp
> +LweSample * addition_multiple(vector<LweSample *> offers, int offerNbr){
Penser à ajouter une petite description de la fonction et des arguments

2022-05-13 16:31 UTC, tiphainehenry commented on src/f_Oracle.cpp
> +LweSample * substraction_multiple( vector<LweSample *> offers, int offerNbr){
idem, ici il faudrait ajouter une description de la nouvelle fonction

2022-05-13 16:31 UTC, tiphainehenry commented on src/utils/url_filenames.json
> -    "ipfs_config":"infura"
mieux vaut mettre le param ipfs_config sur infura

2022-05-18 19:44 UTC, OsgoodSchlatter commented on src/utils/verif_FHE_comparison.cc
> +            case 0:
à rien, j'ai enlevé. (c'était enprévision des prochaines fonctions de calcul).

2022-05-18 19:44 UTC, OsgoodSchlatter commented on README.md
> +# fhe_oracle
ok

2022-05-18 19:47 UTC, OsgoodSchlatter commented on src/utils/url_filenames.json
> -    "ipfs_config":"infura"
done

2022-05-18 19:47 UTC, OsgoodSchlatter commented on src/f_Oracle.cpp
> +LweSample * addition_multiple(vector<LweSample *> offers, int offerNbr){
ok

2022-05-18 19:47 UTC, OsgoodSchlatter commented on src/f_Oracle.cpp
> +LweSample * substraction_multiple( vector<LweSample *> offers, int offerNbr){
ok

2022-05-19 08:08 UTC, tiphainehenry approved these changes

2022-05-19 08:08 UTC, merged